{
 "title": "nebula",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "storage副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nebula_storage_add_edge_error_qps_avg_3600)"
    }
   ]
  },
  {
   "title": "graphd副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nebula_graphd_all_error_qps_avg_3600)"
    }
   ]
  },
  {
   "title": "metad副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nebula_metad_heartbeat_latency_count_3600)"
    }
   ]
  },
  {
   "title": "GO执行个数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_go_latency_count_60"
    }
   ]
  },
  {
   "title": "插入vertex数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_qps_sum_60"
    }
   ]
  },
  {
   "title": "插入edge数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_edge_qps_count_60"
    }
   ]
  },
  {
   "title": "Insert Edges Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_edge_latency_avg_60/1000"
    }
   ]
  },
  {
   "title": "Insert Vertex Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_latency_avg_60/1000"
    }
   ]
  },
  {
   "title": "Go Error QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_go_error_qps_avg_60"
    }
   ]
  },
  {
   "title": "Go Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_go_latency_avg_60/1000"
    }
   ]
  },
  {
   "title": "insert edge error qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_edge_error_qps_avg_5"
    }
   ]
  },
  {
   "title": "Insert Vertex Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_latency_avg_60/1000"
    }
   ]
  },
  {
   "title": "Insert Vertex Error QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_error_qps_avg_60"
    }
   ]
  }
 ]
}